/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchRouteRouteImport } from './routes/match/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdIndexRouteImport } from './routes/match/$matchId/index'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRouteRoute = MatchRouteRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdIndexRoute = MatchMatchIdIndexRouteImport.update({
  id: '/$matchId/',
  path: '/$matchId/',
  getParentRoute: () => MatchRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match': typeof MatchRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match': typeof MatchRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/match': typeof MatchRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/match' | '/mcp' | '/match/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/match' | '/mcp' | '/match/$matchId'
  id: '__root__' | '/' | '/match' | '/mcp' | '/match/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchRouteRoute: typeof MatchRouteRouteWithChildren
  McpRoute: typeof McpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/': {
      id: '/match/$matchId/'
      path: '/$matchId'
      fullPath: '/match/$matchId/'
      preLoaderRoute: typeof MatchMatchIdIndexRouteImport
      parentRoute: typeof MatchRouteRoute
    }
  }
}

interface MatchRouteRouteChildren {
  MatchMatchIdIndexRoute: typeof MatchMatchIdIndexRoute
}

const MatchRouteRouteChildren: MatchRouteRouteChildren = {
  MatchMatchIdIndexRoute: MatchMatchIdIndexRoute,
}

const MatchRouteRouteWithChildren = MatchRouteRoute._addFileChildren(
  MatchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchRouteRoute: MatchRouteRouteWithChildren,
  McpRoute: McpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
